### ISSUE TITLE
ENH: generalize and export fetch output 

### ISSUE THREAD

**Issue by patr1ckm** [civisanalytics/civis-r#100]
We have an un-exported utility function `fetch_output`. It seems useful to generalize and expose it to users:

```
fetch_output(job_id, run_id, name = NULL, using = readRDS)
```
Providing the `name` returns an object of that name. The file id is passed to `read_civis` with an appropriate argument to `using`.

Does it matter if `scripts`, `containers` or `custom` is used?

**Comment by keithing** [comment]
Yeah, that would be great.  It would also be really nice if we had a default of `run_id=NULL` and it just grabs the output from the most recent run.

**Comment by keithing** [comment]
This could be pretty simple if we only returned a file id, allowing users to compose function (so they could use `read_civis` or `download_civis` if needed).  The function could simply return all the outputs of script identified by name (defaulting to the most recent run).

```r
>>> job_id <- -999999
>>> x = fetch_output_file_ids(job_id, run_id=NULL)
>>> x

$some_image.png
[1] 39023

$some_data.json
[1] 232

>>> df = read_civis(x, using = jsonlite::fromJSON)
```

**Comment by patr1ckm** [comment]
Ohhhhh I love that!

**Comment by hinnefe2** [comment]
Just chiming in with a +1 for exposing the function - I literally just wrote a function to do this myself.
