### ISSUE TITLE
dbplyr connection for Civis Redshift tables

### ISSUE THREAD

**Issue by JosiahParry** [civisanalytics/civis-r#116]
Hey, I like being able to read in data from schemas within Civis. However, for large schemas and analyses I think it would be very helpful to have a connection that could be accessed from `RPostgresSQL`, as is shown in the [Amazon documentation](https://aws.amazon.com/blogs/big-data/connecting-r-with-amazon-redshift/).

This would be very helpful when querying large databases/schema and would prevent using large amounts of ram / disk space.

**Comment by keithing** [comment]
Hi @JosiahParry, I agree this is a cool feature.  In fact, we previously we worked on a `dbplyr` connection backend. You can see the documentation with

```
civis::dbi_driver
civis::DBI
```

However, we didn't have many users of the functionality and maintaining it became difficult as there were repeatedly breaking changes in the dependencies.  So, as of now, this functionality exists in an as-in state.  We don't plan to remove it, but we aren't planning to actively maintain it going forward.

The implementation, by the way, relies on the same API calls as functions like `read_civis`, so there won't be performance gains like a direct connection to Redshift.  The scope of `civis-r` is to build convenience tools around the Platform REST API.  If you'd like to talk about direct connections to Redshift, you can reach out to support [at] civisanalytics.
