### ISSUE TITLE
ENH: write_civis_file.data.frame

### ISSUE THREAD

**Issue by patr1ckm** [civisanalytics/civis-r#126]
What would you think about having this generic? It would write the data frame as a csv to S3 by default. Extra args get passed to `write.csv`, and `row.names = FALSE` will be the default.

This would also work for `tbl_df`, `tbl` produced from e.g. `read_csv` since the objects inherit from `data.frame`:

```
xx <- read_csv("~/test/data.csv")
str(xx)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	20 obs. of  3 variables:
 $ X1      : int  1 2 3 4 5 6 7 8 9 10 ...
 $ genre_id: int  13 9 4 18 10 16 19 3 8 7 ...
 $ genre   : chr  "Musical" "Fantasy" "Children" "War" ...
 - attr(*, "spec")=List of 2
  ..$ cols   :List of 3
  .. ..$ X1      : list()
  .. .. ..- attr(*, "class")= chr  "collector_integer" "collector"
  .. ..$ genre_id: list()
  .. .. ..- attr(*, "class")= chr  "collector_integer" "collector"
  .. ..$ genre   : list()
  .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
  ..$ default: list()
  .. ..- attr(*, "class")= chr  "collector_guess" "collector"
  ..- attr(*, "class")= chr "col_spec"
```

And 

```
str(dplyr::as.tbl(data.frame(a=1)), 1)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  1 variable:
 $ a: num 1
```
Since we know that `data.frame` is a tabular thing, it makes sense to store it on S3 in a platform independent way by default rather than using the R specific serialization. Some space would be traded off.

An alternative is `feather`, which would preserve factors better. However, the other side still has to know that `feather` is being used, and I'm not sure this really solves the problem.

@keithing for comments.

**Comment by keithing** [comment]
I've heard users ask for this.  It's a breaking change if we switch the default behavior, but I can be convinced.

**Comment by patr1ckm** [comment]
Oh that's right, I don't want that. That would break a ton of `read_civis` calls, unless we can deduce that it was a CSV.

**Comment by patr1ckm** [comment]
We're going to add this feature / breaking change for `2.0.0`.
