### ISSUE TITLE
BUG: await_all fails

### ISSUE THREAD

**Issue by patr1ckm** [civisanalytics/civis-r#171]
`await_all` is failing this example:

```
ids <- c(23820523, 23820523)
runs <- c(130390319, 130390319)
await_all(scripts_get_r_runs, .x = ids, .y = runs)
```

I think this has to do with passing args to `call_once` and `safe_call_once`. This will require a little refactoring of the existing `call_once` and maybe the tests as well.

@Zephyraith would you be up to taking a look?

**Comment by Zephyraith** [comment]
Can do!

**Comment by Zephyraith** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [debug civis::await_all()](https://trello.com/c/kTijPuJU/51-debug-civisawaitall)
