### ISSUE TITLE
[BUG] civis::files_get() returns bad URL with link_expires_at param

### ISSUE THREAD

**Issue by cwang23** [civisanalytics/civis-r#192]
I had a container script running successfully with this line:
`deck_url <- civis::files_get(file_id, link_expires_at = (Sys.Date() + 2))`

After the `civis-r` package was updated to version `2.0.0`, my container script started failing (tagged to the `latest` docker image).

This was the error message in the logs:
```
2019-06-25 07:21:19 PM Error in call_api("GET", path, path_params, query_params, body_params) : 
2019-06-25 07:21:19 PM   Not Found (HTTP 404). Failed to GET https://api.civisanalytics.com/files/40998851?link_expires_at=2019-06-28. The requested endpoint could not be found.
2019-06-25 07:21:19 PM Calls: <Anonymous> -> call_api -> stop_for_status
2019-06-25 07:21:19 PM Execution halted
2019-06-25 07:21:19 PM Title: QC Ballot Toplines 2019-06-26
```

It seems like having an argument for `link_expires_at` caused it to get pasted to the output `fileUrl` link?

When I re-ran the same script and removed the `link_expires_at` argument with the line changed to this:
`deck_url <- civis::files_get(file_id)`
The container ran successfully with the `civisanalytics/civisverse` Docker image and `latest` image tag.

**Comment by patr1ckm** [comment]
`link_expires_at` returns a 404 when the date provided exceeds 36 hours, and it should do this regardless of what version of `civis` and what image is used.

 I'm not sure exactly what the platform default is for time when only the date is specified, but it seems like `Sys.Date() + 2` could exceed 36 hours depending on when you run the script. So for instance, this morning `Sys.Date() + 2` works for me.

`files_get(id, link_expires_at = Sys.time() + 36 * 60 * 60)` (adding 36 hours explicitly) should fix this, but if something is amiss let me know.

**Comment by cwang23** [comment]
Ah ok got it -- it probably had a successful run before because of when I kicked it off! Thank you for clarifying!!
