### ISSUE TITLE
ENH: Add list of API calls used in each function

### ISSUE THREAD

**Issue by alexm1309** [civisanalytics/civis-r#193]
When users want to scope API keys it can be challenging to figure out exactly which verbs and endpoints are required for a specific API client function.  For example write_civis() includes a POST to /files, a POST to /jobs/:id/runs, and a POST to /imports, but the documentation doesn't make it clear all that's involved so the user has to do a lot of tinkering to figure out exactly what's involved.

**Comment by patr1ckm** [comment]
Interesting! I can see that. What would the ideal method for communicating this be for you? In the web docs of the function? In a specific page for html docs? In redshift?

**Comment by keithing** [comment]
That sort of documentation could be a little difficult to maintain.  I can imagine it would be very easy to add new functions and forget to add this extra documentation.  In general, I think best practice here would be to log the http requests directly.  `civis` uses `httr` so we can add a hook to `httr` to produce logs.  For example:

_(Quick Side Note: be careful that all the logs produced below will contain your api key)_

```r
library(civis)                                                                                                                                                
httr::set_config(httr::verbose())                                               
df <- read_civis(sql("SELECT 1"), database="redshift-general") 
```
Prints all the logs, including:

```
-> GET /databases/ HTTP/1.1^M 
-> GET /credentials/?default=TRUE
-> POST /scripts/sql HTTP/1.1^M  
```

So my advice for this would be 
1. to add the `httr::set_config(httr::verbose())` hook to the script of calls they need to make
2. write that output to a log file
3. search the logs for `GET`, `POST`, `PUT` and `PATCH`.

Using a linux/mac command line:

```bash
Rscript my_script_with_hook.R >log.txt 2>&1
cat log.txt | grep "GET\|POST\|PUT\|PATCH"
```
