### ISSUE TITLE
ENH: Point civis_ml script templates to aliases

### ISSUE THREAD

**Issue by patr1ckm** [civisanalytics/civis-r#202]
Instead of hard coding CivisML template ids, we can point to aliases (to be developed). The aliases will be updated as part of releases, so if the client points to the “most current version” alias, we won’t need a client release to coordinate with a CivisML release.

This is blocked by CivisML template aliases being released.

**Comment by jacksonllee** [comment]
CivisML template aliases are now publicly available 🎉 . The civis-python has just been updated to start using them in the next release: https://github.com/civisanalytics/civis-python/pull/341
