### ISSUE TITLE
Is there any use in writing a file locally first before calling `write_civis_file`?

### ISSUE THREAD

**Issue by crich011** [civisanalytics/civis-r#211]
I have a utility function which takes an object as an argument and outputs a file ID on S3, much like `write_civis_file` (which it calls under the hood after first writing the given file locally). Is there any utility to this? I feel like the reason I did it this way is just that someone's code who I inherited did it that way for powerpoint documents, rather than there being a particularly good reason.

The resolution to this issue might just be an answer of "no, it is not useful".

**Comment by patr1ckm** [comment]
If I understand correctly, `write_civis_file(obj)` already does this. It serializes the file, and returns the file id on S3 after uploading. I don't think a wrapper is needed.

One thing I can imagine is that it can be slightly annoying to save and cleanup objects in temporary files. We have a utility `with_tempfile` for doing so. Maybe exporting would be helpful? 

For example:
```
with_tempfile(function(fn, obj) { 
  saveRDS(fn)
  write_civis_file(fn)
})
```

**Comment by crich011** [comment]
Makes sense! Maybe surfacing that tempfile utility would be useful? But I defer to you on that; happy to close this issue if you're not especially keen on surfacing `with_tempfile`.

**Comment by patr1ckm** [comment]
Since this is already a function in http://withr.r-lib.org/reference/with_tempfile.html, I doubt exporting will gain very much.
