### ISSUE TITLE
DOC: Documentation on CASS/NCOA endpoint not complete

### ISSUE THREAD

**Issue by alexm1309** [civisanalytics/civis-r#220]
For the documentation on creating a CASS/NCOA job the source and destination parameters have incomplete documentation.  They only mention the databaseTable object but not the parameters within that object.

https://civisanalytics.github.io/civis-r/reference/enhancements_post_cass_ncoa.html

Here's the link to the same call in the Python Client for reference - https://civis-python.readthedocs.io/en/latest/api_resources.html#civis.resources._resources.Enhancements.post_cass_ncoa

**Comment by patr1ckm** [comment]
Thanks for the report!
