### ISSUE TITLE
Is this repo and the 'civis' package maintained?

### ISSUE THREAD

**Issue by HenrikBengtsson** [civisanalytics/civis-r#246]
Is this repo and the **civis** package maintained?

I see that the last commit to this repo is from June 22, 2020. Except for my recent issues (#244 and #245), the last issue comment is 
from June 22, 2020 (same date).

Can you please reply asap to this to confirm it is still maintained?  If not, I'll go ahead a make updates to my **future** package (#244 and #245) that will break **civis**, causing it to fall off CRAN. If **civis** is still maintained, I'm willing to wait a bit longer to give you a chance to update **civis**.

**Comment by pcooman** [comment]
Hi @HenrikBengtsson,

Thank you for the heads-up! Yes, I can confirm that the [civis-r repo](https://github.com/civisanalytics/civis-r) and the `civis` package are still maintained.

I will investigate the issues you raise, make the necessary changes and publish an updated version of `civis` to CRAN. If you could hold off on updating the `future` package for a while longer, I would greatly appreciate it (1 week should be enough time)! I will let you know as soon as I have made the updates on our end.

**Comment by HenrikBengtsson** [comment]
Thanks for confirming. I'll hold back and wait for **civis** to be updated.  FWIW, the updates should be "quick and easy".
