### ISSUE TITLE
`expires_at` default could be confusing

### ISSUE THREAD

**Issue by keithing** [civisanalytics/civis-r#51]
Due to the nature of the API, in some circumstances explicitly passing `parameter=NULL` is different than not passing the parameter at all.  This isn't the convention of the R language and is particularly problematic with the `write_civis_file`, since the default is have files expire in 30 days.

@patr1ckm, I can think of two options to get around this:

1) Make this distinction more clear in the docs
2) Change the default in `write_civis_file` to a sentinel value like `"DEFAULT"`

Thoughts on this?

cc @harader for raising this issue offline.

**Comment by patr1ckm** [comment]
It's true, I think we should make an exception here to solve this issue. We can keep the sentinel value as `NULL`, but then use another special value like `Inf` to signal keeping the file indefinitely. so

`write_civis_file(..., expires_at = NULL)` -> 30 days
`write_civis_file(..., expires_at = Inf)` -> store indefinitely
